// Code generated by "stringer -type=HashID"; DO NOT EDIT.

package qrsecrets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HashSHA256-0]
	_ = x[HashSHA512-1]
	_ = x[HashSHA3_256-2]
	_ = x[HashSHA3_512-3]
}

const _HashID_name = "HashSHA256HashSHA512HashSHA3_256HashSHA3_512"

var _HashID_index = [...]uint8{0, 10, 20, 32, 44}

func (i HashID) String() string {
	if i >= HashID(len(_HashID_index)-1) {
		return "HashID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HashID_name[_HashID_index[i]:_HashID_index[i+1]]
}
